import re
str= "my name is manoj 123"
b=re.findall("\\Amy",str)
a=re.findall("123\\Z",str)
c=re.findall("\\s",str)
d=re.findall("\\S",str)
e=re.findall("\\d",str)
f=re.findall("\\D",str)
g=re.findall("\\w",str)
h=re.findall("\\W",str)
i=re.findall("\\bman",str)
j=re.findall("oj\\B",str)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
